# Generated by Django 3.1.7 on 2021-04-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210402_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='MySetting',
        ),
    ]
